---
title: "First inspection of German Microcensus Datenstrukturfile"
author: "Felix Zaussinger"
date: "31.03.2022"
output: 
  bookdown::html_document2:
    toc: true
    toc_depth: 2
    number_sections: true
    df_print: paged
    code_folding: hide
---

```{r setup, include=FALSE, results='hide'}

# set working directory (has to be changed at GWAP)
rootdir = "T:/Documents/Projects/04_jrc_green-skills-regional/03_data-analysis/re4gt"

# set knitr options
knitr::opts_knit$set(root.dir = rootdir)
knitr::opts_chunk$set(echo=TRUE, warning=FALSE, message=FALSE, results='asis')
options(digits=4)

# remove all objects from R workspace
rm(list=ls())

# Load necessary packages
library(tidyverse)
library(readxl)

# set plotting theme
theme_set(theme_classic())

```

```{r, load_data, include=FALSE}

fpath_dsf_csv <- file.path(getwd(), "data", "raw", "lfs", "de", "DSF_MZ 2019.CSV")

# read DSF, csv version
dsf_csv <- read.csv(
  file=fpath_dsf_csv,
  header=TRUE,
  sep=";",
  strip.white=TRUE
)

dsf_csv

```


# Header  {-}
_description_

***
__More in-depth description with bullets__

* bullet 1
* bullet 2
    + sub-bullet 1
    + sub-bullet 2

***

```{r, include=FALSE}
# Note:
# ------
# Figures are referenced by simply referring to the name of the code block: _(figure \@ref(fig:A))_.
# Figure panels can be created by adding _..., fig.show = 'hold', out.width = '50%'_ to the curly brackets of the code block.
# Example: {r blockname, fig.cap="figure capture", fig.show = 'hold', out.width = '50%'}

# output table
#htmlreg(list(m1, m2), 
#        custom.model.names = c('m1', 'm2),
#        caption="", label="tab:", center = FALSE, star.symbol = "\\*")
```

## Task 1 {-}
```{r}

```

