# -------------------------------------------------------------------------------------
# ESCO
# -------------------------------------------------------------------------------------
ESCO:
  LANGUAGE: "en"
  VERSION: "v1.1.0"
  VERSION_NEWEST: "v1.1.0"
  WEIGHT_UNIFORM: 1
  WEIGHT_ESSENTIAL_SKILL: 1
  WEIGHT_OPTIONAL_SKILL: 0.5

# -------------------------------------------------------------------------------------
# EU-LFS
#   n_digits_isco08: int
#     Number of digits in ISCO-08 occupation classification. Needs to be in [2, 4].
# -------------------------------------------------------------------------------------
lfs_eu:
  n_digits_isco08: 3
  n_digits_nace: 1
  n_digits_nuts: 2
  years: ["2019"]
  countries: [
    "AT", "BE", "BG", "CH", "CY", "CZ", "DE", "DK", "EE", "ES", "FI", "FR", "GR", "HR",
    "HU", "IE", "IS", "IT", "LT", "LU", "LV", "MT", "NL", "NO", "PL", "PT", "RO", "SE",
    "SI", "SK", "UK"
  ]
  variables: [
    "WSTATOR", "SEX", "NACE1D", "ISCO3D", "COUNTRYW", "REGIONW", "FTPT", "REFYEAR",
    "COUNTRY", "REGION", "DEGURBA", "HHTYPE", "AGE", "ILOSTAT", "EDUC4WN", "HATLEV1D",
    "MAINSTAT", "INCDECIL", "COEFF"
  ]
  na_values: [9, 99, 999, 9999]
  dtypes: {
    "WSTATOR": "category",
    "SEX": "category",
    "NACE1D": "category",
    "ISCO3D": "category",
    "COUNTRYW": "category",
    "REGIONW": "category",
    "FTPT": "category",
    "REFYEAR": "int",
    "COUNTRY": "category",
    "REGION": "category",
    "DEGURBA": "category",
    "HHTYPE": "category",
    "AGE": "int",
    "ILOSTAT": "category",
    "EDUC4WN": "category",
    "HATLEV1D": "category",
    "MAINSTAT": "category",
    "INCDECIL": "float"
}
