PATHS_MAIN:
  DATA_RAW: ""
  DATA_INTERIM: ""
  DATA_PROCESSED: ""
  DATA_EXTERNAL: ""
  CONFIGS: ""
  RESULTS_FIGURES: ""
  RESULTS_TABLES: ""
  RESULTS_REPORTS: ""

CROSSWALKS:
  ONET_ESCO: "data\\raw\\mapping-career-causeways\\codebase\\data\\processed\\ESCO_ONET_xwalk_full.csv"

# EU-LFS Data PATHS_EULFS
EU_LFS:
  FPATH_RAW: "C:\\eurostat_data\\raw"
  FPATH_RAW_YF: "C:\\eurostat_data\\raw\\Yearly_Data\\YearlyFiles_83_2019\\_YearlyFiles"
  FPATH_INTERIM: "C:\\eurostat_data\\interim"
  FPATH_PROCESSED: "C:\\eurostat_data\\processed"

# ESCO Skill Weights
ESCO:
  LANGUAGE: "en"
  VERSION: "v1.0.3"
  VERSION_NEWEST: "v1.1.0"
  WEIGHT_UNIFORM: 1
  WEIGHT_ESSENTIAL_SKILL: 1
  WEIGHT_OPTIONAL_SKILL: 0.5

# Transition Analysis Parameters
TRANSITION_ANALYSIS:
  MIN_VIABLE: 0.3
  HIGHLY_VIABLE: 0.4
  MAX_JOB_ZONE_DIF: 1
  MIN_EARNINGS_RATIO: 0.75