# EU-LFS Data
metadata:
  relative_paths: ["path_crosswalk"]
  absolute_paths: ["path_eulfs"]

path_eulfs:
  raw: "C:\\eurostat_data\\raw"
  raw_yf: "C:\\eurostat_data\\raw\\Yearly_Data\\YearlyFiles_83_2019\\_YearlyFiles"
  interim: "C:\\eurostat_data\\interim"
  processed: "C:\\eurostat_data\\processed"

# Note: relative paths need to start one level below the project directory to be parsed correctly
path_crosswalk:
  onet_esco: "data\\raw\\mapping-career-causeways\\codebase\\data\\processed\\ESCO_ONET_xwalk_full.csv"